[mypy]
python_version = 3.11
strict = False
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
disallow_untyped_defs = False
check_untyped_defs = True
ignore_missing_imports = True
exclude = agent_env/|\.virgo_memory/|_test_

[mypy.plugins.*]
; no plugins
