"""
virgo_testgen — generate pytest test stubs from Python source files.

Scans Python files using AST, extracts functions and class methods,
and generates ``pytest``-style test files with placeholder stubs.

Usage::

    virgo testgen --path ./module.py
    virgo testgen --dir ./src --output ./tests --overwrite
    python virgo_testgen.py --path ./module.py
"""

from __future__ import annotations

import argparse
import ast
import os
import sys
from pathlib import Path
from typing import Iterator

from _console import icon
from _log import log

HERE = Path(__file__).parent

# ---------------------------------------------------------------------------
# AST extraction
# ---------------------------------------------------------------------------


def _extract_functions(tree: ast.Module, source: str) -> list[dict[str, str]]:
    """Return a list of top-level function names and any docstring snippets."""
    items: list[dict[str, str]] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef):
            doc = ast.get_docstring(node) or ""
            items.append({
                "name": node.name,
                "type": "function",
                "doc": doc.split("\n")[0] if doc else "",
            })
        elif isinstance(node, ast.AsyncFunctionDef):
            doc = ast.get_docstring(node) or ""
            items.append({
                "name": node.name,
                "type": "async_function",
                "doc": doc.split("\n")[0] if doc else "",
            })
    return items


def _extract_classes(tree: ast.Module, source: str) -> list[dict[str, str | list[dict]]]:
    """Return a list of classes with their methods."""
    classes: list[dict[str, str | list[dict]]] = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef):
            methods: list[dict[str, str]] = []
            for item in ast.iter_child_nodes(node):
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    doc = ast.get_docstring(item) or ""
                    methods.append({
                        "name": item.name,
                        "type": "method",
                        "doc": doc.split("\n")[0] if doc else "",
                    })
            doc = ast.get_docstring(node) or ""
            classes.append({
                "name": node.name,
                "type": "class",
                "doc": doc.split("\n")[0] if doc else "",
                "methods": methods,
            })
    return classes


def analyze_file(path: Path) -> dict:
    """Parse *path* with AST and return structured metadata.

    Returns a dict with keys:
        - path
        - functions (list of {name, type, doc})
        - classes (list of {name, type, doc, methods})
    """
    source = path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(source, filename=str(path))
    except SyntaxError as exc:
        log.warning("Syntax error in %s: %s", path.name, exc)
        return {"path": str(path), "functions": [], "classes": []}

    return {
        "path": str(path),
        "functions": _extract_functions(tree, source),
        "classes": _extract_classes(tree, source),
    }


# ---------------------------------------------------------------------------
# Test generation
# ---------------------------------------------------------------------------


def _safe_module_name(path: Path) -> str:
    """Derive a safe module name from *path* (e.g. 'virgo_testgen')."""
    stem = path.stem
    # Replace non-identifier characters with underscores
    safe = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in stem)
    if safe and safe[0].isdigit():
        safe = f"_{safe}"
    return safe or "module"


def _generate_test_content(analysis: dict, rel_path: str) -> str:
    """Generate pytest test file content for one Python module."""
    module_name = _safe_module_name(Path(analysis["path"]))
    lines: list[str] = []
    lines.append(f'"""Tests for {rel_path} — auto-generated by virgo testgen."""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("import pytest")
    lines.append("")

    # Import the module under test
    import_path = rel_path.replace(os.sep, ".").replace("/", ".").replace("\\", ".")
    if import_path.endswith(".py"):
        import_path = import_path[:-3]
    lines.append(f"import {import_path}  # module under test")
    lines.append("")

    # ----- Functions -----
    for fn in analysis.get("functions", []):
        name = fn["name"]
        # Skip private / dunder
        if name.startswith("_"):
            continue
        doc = fn.get("doc", "")
        stub_doc = f" # {doc}" if doc else ""
        lines.append("")
        lines.append(f"def test_{name}():")
        lines.append(f'    """Test {name}{stub_doc}."""')
        lines.append(f"    # TODO: implement")
        lines.append(f"    assert True")
        lines.append("")

    # ----- Classes -----
    for cls in analysis.get("classes", []):
        cls_name = cls["name"]
        for method in cls.get("methods", []):
            mname = method["name"]
            if mname.startswith("_"):
                continue
            doc = method.get("doc", "")
            stub_doc = f" # {doc}" if doc else ""
            lines.append("")
            lines.append(
                f"def test_{cls_name}_{mname}():"
            )
            lines.append(f'    """Test {cls_name}.{mname}{stub_doc}."""')
            lines.append(f"    # TODO: implement")
            lines.append(f"    assert True")
            lines.append("")

    return "\n".join(lines)


def generate_tests(
    path: str | Path,
    output_dir: str | Path = "./tests",
    overwrite: bool = False,
) -> list[Path]:
    """Generate test files for the Python source at *path*.

    Parameters
    ----------
    path:
        File or directory to scan.  Directories are walked recursively.
    output_dir:
        Directory where test files are written.
    overwrite:
        If True, overwrite existing test files without warning.

    Returns
    -------
    List of Paths to generated test files.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    source_path = Path(path)
    if not source_path.exists():
        log.error("Path does not exist: %s", source_path)
        return []

    # Collect Python files
    if source_path.is_file():
        py_files = [source_path] if source_path.suffix == ".py" else []
    else:
        py_files = sorted(source_path.rglob("*.py"))

    if not py_files:
        log.warning("No .py files found at %s", source_path)
        return []

    generated: list[Path] = []

    for py_file in py_files:
        log.info("Analyzing %s", py_file)
        analysis = analyze_file(py_file)

        # Determine relative path for import statement
        try:
            rel = py_file.relative_to(source_path.parent if source_path.is_file() else source_path)
        except ValueError:
            rel = py_file.name

        content = _generate_test_content(analysis, str(rel))
        if not content.strip():
            log.info("  Skipped %s (no public symbols)", py_file.name)
            continue

        test_name = f"test_{py_file.stem}.py"
        out_file = output_path / test_name

        if out_file.exists() and not overwrite:
            log.warning("  Skipped (exists, use --overwrite): %s", out_file)
            continue

        out_file.write_text(content, encoding="utf-8")
        generated.append(out_file)
        log.info("  -> %s", out_file)

    return generated


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> None:
    """CLI entry point for ``virgo testgen``."""
    parser = argparse.ArgumentParser(
        prog="virgo testgen",
        description="Generate pytest test stubs from Python source files.",
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--path", "-p",
        help="Single Python file to analyze.",
    )
    group.add_argument(
        "--dir", "-d",
        help="Directory to scan recursively for .py files.",
    )
    parser.add_argument(
        "--output", "-o",
        default="./tests",
        help="Output directory for generated test files (default: ./tests).",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing test files without warning.",
    )

    args = parser.parse_args(argv)

    source = args.path or args.dir
    if not source:
        parser.print_help()
        sys.exit(1)

    print(f"\n{icon('test')}  Generating tests from: {source}")
    results = generate_tests(
        path=source,
        output_dir=args.output,
        overwrite=args.overwrite,
    )

    if results:
        print(f"\n  {icon('ok')}  Generated {len(results)} test file(s) in {args.output}/")
        for f in results:
            print(f"     {icon('file')} {f}")
        print()
    else:
        print(f"\n  {icon('info')}  No test files were generated.\n")


if __name__ == "__main__":
    main()
